version: '3.1'

services:

  wordpress:
    image: wordpress:6.1.1
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: host
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_pass
      WORDPRESS_DB_NAME: db
      WORDPRESS_DEBUG: 1
    volumes:
      - ./themes/arkon-theme:/var/www/html/wp-content/themes/arkon-theme
      - ./uploads:/var/www/html/wp-content/uploads

  host:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./data:/var/lib/mysql

volumes:
  wordpress:
  host: